### ISSUE TITLE
BUG04 - Aplicar colores a titulos

### ISSUE THREAD

**Issue by manuel-morales-sa** [manuel-morales-sa/MISW4203-Vinilos#62]
Se presenta un error en los colores de los titulos de el detalle, ya que no se ven del color turqueza que esta en el diseño.

<img width="352" alt="Screen Shot 2022-11-20 at 1 02 14 AM" src="https://user-images.githubusercontent.com/98921573/202888382-cbd65e9a-3e2b-4b65-9b85-4a5e4ae514dc.png">

**Comment by JosePalacioM** [comment]
Se corrigen los colores de los títulos de los detalles de los artistas y se ponen en azul turqueza.

![image](https://user-images.githubusercontent.com/98669202/204160866-dfc204e6-ebe4-4983-b4e2-4d00120f0710.png)
